name: Build and Upload cmip6_preprocessing to PyPI
on:
  release:
    types:
      - published

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'jbusecke/cmip6_preprocessing'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools setuptools-scm[toml] wheel twine
      - name: Check python version
        run: |
          python --version
      - name: Check current package version
        run: |
          python setup.py --version
      - name: Build tarball and wheels
        run: |
          git clean -xdf
          git restore -SW .
          python setup.py sdist bdist_wheel
      - name: Check built artifacts
        run: |
          python -m twine check dist/*
          pwd
          if [ -f dist/cmip6_preprocessing-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: releases
          path: dist
  test-built-dist:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8
      - uses: actions/download-artifact@v2
        with:
          name: releases
          path: dist
      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist
  upload-to-testpypi:
    needs: test-built-dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: releases
          path: dist
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TESTPYPI_TOKEN }}
          verbose: true
  upload-to-pypi:
    needs: upload-to-testpypi
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: releases
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
